server:
  port: 80

eureka:
  instance:
    hostname: eurekaServer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:80/eureka/
